# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170622_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('upload', models.FileField(blank=True, null=True, upload_to='static/pdf/Highlight')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='static/pdf/Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='static/pdf/notice_board'),
        ),
    ]
