# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170622_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='home/static/pdf/Event'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='home/static/pdf/Highlight'),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='home/static/pdf/notice_board'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='upload',
            field=models.ImageField(upload_to='home/static/img/buildings'),
        ),
    ]
