# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170626_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='btech_specialization',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='description',
            new_name='btech_university',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='btech_year',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='industry_experience',
            field=models.IntegerField(blank=True, help_text='enter the number only and dont add anything else', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='masters_specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='masters_university',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='masters_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='research_experience',
            field=models.IntegerField(blank=True, help_text='enter the number only and dont add anything else', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='research_interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='research_paper_published',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='summary',
            field=models.TextField(blank=True, help_text='write a summary about yourself', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teaching_experience',
            field=models.IntegerField(blank=True, help_text='enter the number only and dont add anything else', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teaching_interest',
            field=models.TextField(blank=True, null=True),
        ),
    ]
