# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 18:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0005_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fathers_name', models.CharField(max_length=40)),
                ('Mothers_name', models.CharField(max_length=40)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=1, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='TeacherProfile',
        ),
        migrations.AddField(
            model_name='attendence',
            name='attendence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.StudentProfile'),
        ),
    ]
