# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('paragraph', models.TextField()),
                ('chairman_name', models.CharField(max_length=40)),
                ('chairman_position', models.CharField(max_length=60)),
                ('vice_chairman_name', models.CharField(max_length=40)),
                ('vice_chairman_position', models.CharField(max_length=60)),
                ('secretary_name', models.CharField(max_length=40)),
                ('secretary_position', models.CharField(max_length=60)),
                ('treasurer_name', models.CharField(max_length=40)),
                ('treasurer_position', models.CharField(max_length=60)),
                ('advisor_name', models.CharField(max_length=40)),
                ('advisor_position', models.CharField(max_length=60)),
                ('director_name', models.CharField(max_length=40)),
                ('diroctor_position', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Aicte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
                ('upload', models.FileField(blank=True, null=True, upload_to='static/pdf/Event')),
            ],
        ),
        migrations.CreateModel(
            name='DirectorsDesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=40)),
                ('director_name_link', models.URLField(blank=True, help_text='link of the page it should direct too', null=True)),
                ('paragraph', models.TextField()),
                ('image', models.ImageField(upload_to='static/img/director')),
            ],
        ),
        migrations.CreateModel(
            name='ImportantFunctionaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VisionAndMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_text', models.TextField()),
                ('mission_text', models.TextField()),
            ],
        ),
    ]
