# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_institute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicte',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='static/pdf/Aicte'),
        ),
    ]
