# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_institute', '0003_auto_20170623_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicte',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='static/pdf/Aicte'),
        ),
        migrations.AlterField(
            model_name='directorsdesk',
            name='image',
            field=models.ImageField(upload_to='static/img/director'),
        ),
    ]
